export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGIN_LOADING = 'AUTH_LOGIN_LOADING';
export const AUTH_LOADING_FINISHED = 'AUTH_LOADING_FINISHED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILED = 'VERIFICATION_FAILED';

export const CLEAN_ERROR = 'CLEAN_ERROR';

// ADMIN 

export const ALL_CATEGORY = 'ALL_CATEGORY';
export const ALL_PRODUCT = 'ALL_PRODUCT';
export const ADMIN_LOADING = 'ADMIN_LOADING';
export const ADMIN_LOADING_FINISHED = 'ADMIN_LOADING_FINISHED';
export const ADMIN_LOADING_ERROR = 'ADMIN_LOADING_ERROR';

export const ADMIN_CLEAN = 'ADMIN_CLEAN'