export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGIN_LOADING = 'AUTH_LOGIN_LOADING';
export const USER_LOGOUT = 'USER_LOGOUT';

export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILED = 'VERIFICATION_FAILED';